language: python

sudo: false

env:
    - TOX_ENV=py37-flake8
    - TOX_ENV=py37-docs
    - TOX_ENV=py37-django2.2-drf3.10

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
