language: python

python:
    - 3.6

sudo: false

env:
    - TOX_ENV=py36-flake8
    - TOX_ENV=py36-docs
    - TOX_ENV=py36-django2.2-drf3.10

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

matrix:
  fast_finish: true

install:
  - pip install tox

script:
    - tox -e $TOX_ENV
