site_name: django-rest-framework-features
site_description: Rapid schema generation, permission management based on named features
repo_url: https://github.com/cloudcode-hungary/django-rest-framework-features
site_dir: html
nav:
    - Home: index.rst
    - Permissions: permissions.rst
    - Schema: schema.rst
    - Settings: settings.rst
    - URLs: urls.rst
theme: readthedocs