site_name: django-rest-framework-features
site_description: Advanced schema generation based on named features
repo_url: https://github.com/cloudcode-hungary/django-rest-framework-features
site_dir: html
nav:
    - Home: index.md
    - Permissions: permissions.md
    - Schema: schema.md
    - Settings: settings.md
    - URLs: urls.md
theme: readthedocs