site_name: djangorestframework-features
site_description: Rapid schema generation, permission management based on named features
repo_url: https://dev.cloudcode.hu/common/django-rest-framework-features
site_dir: html
nav:
    - Home: index.md
    - Schema: schema.md
    - Permissions: permissions.md
theme: readthedocs